name: CI
on: [push, pull_request]

jobs:
  build:
    name: AVR-GCC
    runs-on: ubuntu-latest
    container: dea82/avr-gcc-docker:1.3.0
    steps:
      - uses: actions/checkout@v2
      - run: .github/workflows/ci_build.sh
