name: CI
on: [push, pull_request]

jobs:
  build:
    name: AVR-GCC
    runs-on: ubuntu-latest
    container: dea82/avr-gcc-docker:1.3.0
    steps:
      - uses: actions/checkout@v2
      - run: .github/workflows/ci_build.sh
      - name: Save build artifacts (master branch only)
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v2
        with:
          name: firmware_hex_all
          path: Firmware/ogx360_32u4/build/*.hex